# Generated by Django 5.1.5 on 2025-02-04 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("foods", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="food",
            options={"verbose_name": "Блюдо", "verbose_name_plural": "Блюда"},
        ),
    ]
